// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20241025080711_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("WebAPI.Data.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bcfa83f9-435e-4903-a9a0-41a1056f91bd"),
                            BirthTime = new DateTime(1985, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Actor One"
                        },
                        new
                        {
                            Id = new Guid("b69d8e13-a56e-41d2-af7a-3628497ce01d"),
                            BirthTime = new DateTime(1990, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Actor Two"
                        });
                });

            modelBuilder.Entity("WebAPI.Data.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b65af4e8-8ff7-4dd1-9f95-6078e27c9e42"),
                            Address = "192.168.1.10",
                            Name = "Machine A",
                            Port = 8080u,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("4bb8e41e-26db-4257-af34-621989e7ebd2"),
                            Address = "192.168.1.11",
                            Name = "Machine B",
                            Port = 8081u,
                            Status = 2
                        });
                });

            modelBuilder.Entity("WebAPI.Data.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaf5c9cd-52bd-4583-b245-f1cabb1bdb06"),
                            Name = "Video One"
                        },
                        new
                        {
                            Id = new Guid("2225e305-a5ff-468b-bf9e-8cb1344cf3df"),
                            Name = "Video Two"
                        });
                });

            modelBuilder.Entity("WebAPI.Data.Video", b =>
                {
                    b.HasOne("WebAPI.Data.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId");

                    b.Navigation("Actor");
                });
#pragma warning restore 612, 618
        }
    }
}
