// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20250519052407_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("WebAPI.Data.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConnectorType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("87cd681b-2bca-479c-bca1-13d2ce0252b7"),
                            Address = "192.168.1.10",
                            ConnectorType = 0,
                            Name = "Machine A",
                            Port = 8080u,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("1f7e75ce-f450-45d4-b34b-2a2f0a394d6a"),
                            Address = "192.168.1.11",
                            ConnectorType = 0,
                            Name = "Machine B",
                            Port = 8081u,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("2e9e3c46-c525-4400-a138-96756406540a"),
                            Address = "opc.tcp://localhost",
                            ConnectorType = 2,
                            Name = "Video One",
                            Port = 4840u,
                            Status = 0
                        });
                });

            modelBuilder.Entity("WebAPI.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("470b1d1b-7ef6-4b76-94a4-4fb93432d9cd"),
                            Name = "admin",
                            Password = "admin"
                        },
                        new
                        {
                            Id = new Guid("c765e603-d56a-4c40-80de-ec53a808335a"),
                            Name = "Default",
                            Password = "Default"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
